services:
    nova:
        build: .
        container_name: nova
        ports:
            - '3005:3005'
        volumes:
            - ./.env:/usr/src/app/.env
        depends_on:
            - postgres
            - keydb
        restart: unless-stopped

    keydb:
        image: eqalpha/keydb:latest
        container_name: keydb
        restart: unless-stopped
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping']
            interval: 1s
            timeout: 5s
            retries: 10

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_DB=nova
            - POSTGRES_USER=nova
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker-data/postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 1s
            timeout: 5s
            retries: 10
