name: Bun

on: [push, pull_request]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Generate migrations
              run: bun run db:generate
            - name: Run tests
              run: bun test --preload ./src/server.ts

    coverage:
        name: Coverage

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Generate migrations
              run: bun run db:generate
            - name: Run tests
              run: bun test --preload ./src/server.ts --coverage
