name: Tests

on: [push]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install
            - name: Run tests
              run: bun test --preload ./src/server.ts
